### ISSUE TITLE
Add JS to generate details to result page from Movie of the Night (result.js)

### ISSUE THREAD

**Issue by ckisi** [ckisi/film-fetcher#29]
When I submit a search for a movie,spisode ,or show. 
The movie, show, or episode details will show up on the next html called results.html

**Comment by jjackson0228** [comment]
added movie details 

![Image](https://github.com/user-attachments/assets/0ebb18f3-7d3f-4db2-ac2c-5dbc939014e1)

https://github.com/ckisi/film-fetcher/pull/62
