### ISSUE TITLE
Customize CSS for background, font, etc. on index.html 

### ISSUE THREAD

**Issue by ckisi** [ckisi/film-fetcher#47]

**Comment by HashemE1999** [comment]
AS a user,

I WANT a visually appealing color scheme and evenly spaced boxes and text

SO THAT my eyes don't bleed when I look at the screen

![Image](https://github.com/user-attachments/assets/62a933d5-ee9b-4a65-afc1-8a08014b88c0)

**Comment by HashemE1999** [comment]
# Pull request link:

## https://github.com/ckisi/film-fetcher/pull/56
