### ISSUE TITLE
Customize CSS for background, font, etc. on result.html

### ISSUE THREAD

**Issue by ckisi** [ckisi/film-fetcher#54]

**Comment by HashemE1999** [comment]
# Link to pull request:

## https://github.com/ckisi/film-fetcher/pull/63

# Screenshots:

## 

![Image](https://github.com/user-attachments/assets/b94df368-1bdc-4e74-bcea-db70ca2d0046)

##

![Image](https://github.com/user-attachments/assets/ca433e5c-9ee6-4959-a90c-c1cee87d0595)
