### ISSUE TITLE
Make a detailed READ.ME

### ISSUE THREAD

**Issue by jjackson0228** [ckisi/film-fetcher#67]
Make a detailed read me with a section for the description of the application, screeshots, how to use app, links to find app link to github repo as well, all tools used like bulma the apis and all kind of code we used, and any sourcees we used like xpert assistance chatgpt and anything else.

**Comment by HashemE1999** [comment]
# Screenshot

## 

![Image](https://github.com/user-attachments/assets/fabd14eb-25aa-4813-abab-707c8396a15f)

# Link to pull request

## https://github.com/ckisi/film-fetcher/pull/74
